import type { Ref } from 'vue'
import type { WeekData } from '../types'

import axios from '@nextcloud/axios'
import { getCapabilities } from '@nextcloud/capabilities'
import { generateUrl } from '@nextcloud/router'
import { normalizeWeekData } from '../utils/weekData'

interface PollDeps {
	currentYear: Ref<number>
	currentWeek: Ref<number>
	weekData: Ref<WeekData>
	editingTask: Ref<{ day: string, taskId: string } | null>
	loadWeek: () => Promise<void>
	loadCustomColumns: () => Promise<void>
	materializeRecurringTasks: () => void
	applyCustomColumnsData: (data: unknown) => void
	isWeekSaveIdle: () => boolean
	isWeekLoadIdle: () => boolean
	isCustomSaveIdle: () => boolean
	getWeekKnownUpdatedAt: () => number
	setWeekKnownUpdatedAt: (val: number) => void
	getCustomKnownUpdatedAt: () => number
	setCustomKnownUpdatedAt: (val: number) => void
}

interface NotifyPushCapability {
	endpoints?: { websocket?: string, pre_auth?: string }
}

const WS_PROBE_TIMEOUT_MS = 5_000

function sameOriginWebSocketUrl() {
	const wsProto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
	return `${wsProto}//${window.location.host}/push/ws`
}

// The notify_push SDK reads its WebSocket URL from the notify_push capability,
// which the server populates from a single fixed `base_endpoint`. That
// hardcoded host doesn't survive being reached over a different name (LAN IP,
// Tailscale, mDNS, localhost), so we rewrite it to the page's own origin and
// rely on Nextcloud's webserver to reverse-proxy /push/* to the notify_push
// backend. The `pre_auth` endpoint is generated by Nextcloud's URL generator
// against the request host, so it's already same-origin and we leave it
// alone.
function rewriteNotifyPushWebsocket(): string | null {
	let caps: { notify_push?: NotifyPushCapability }
	try {
		caps = getCapabilities() as { notify_push?: NotifyPushCapability }
	} catch {
		return null
	}
	if (!caps?.notify_push) {
		return null
	}

	const websocket = sameOriginWebSocketUrl()
	caps.notify_push.endpoints = { ...(caps.notify_push.endpoints ?? {}), websocket }
	return websocket
}

function probeWebSocket(url: string, timeoutMs = WS_PROBE_TIMEOUT_MS): Promise<boolean> {
	return new Promise((resolve) => {
		let settled = false
		let socket: WebSocket | null = null
		const timerHolder: { id: ReturnType<typeof setTimeout> | null } = { id: null }
		const finish = (ok: boolean) => {
			if (settled) {
				return
			}
			settled = true
			if (timerHolder.id !== null) {
				clearTimeout(timerHolder.id)
			}
			try {
				socket?.close()
			} catch {
				/* ignore */
			}
			resolve(ok)
		}
		timerHolder.id = setTimeout(() => finish(false), timeoutMs)
		try {
			socket = new WebSocket(url)
		} catch {
			finish(false)
			return
		}
		socket.onopen = () => finish(true)
		socket.onerror = () => finish(false)
		socket.onclose = () => finish(false)
	})
}

export function usePolling(deps: PollDeps) {
	let weekPollAbortController: AbortController | null = null
	let shouldPollWeek = false
	let customPollAbortController: AbortController | null = null
	let shouldPollCustom = false
	let usingNotifyPush = false

	// --- Week polling ---

	function stopWeekPoll() {
		shouldPollWeek = false
		weekPollAbortController?.abort()
		weekPollAbortController = null
	}

	async function longPollWeek() {
		if (!shouldPollWeek) {
			return
		}
		const controller = new AbortController()
		weekPollAbortController = controller
		try {
			const url = generateUrl('/apps/weekplanner/week/{year}/{week}/poll', {
				year: String(deps.currentYear.value),
				week: String(deps.currentWeek.value),
			})
			const response = await axios.get<{ changed: boolean, updatedAt: number, data?: unknown }>(
				`${url}?since=${deps.getWeekKnownUpdatedAt()}`,
				{ signal: controller.signal, timeout: 35_000 },
			)
			if (response.data.changed && response.data.data !== undefined && response.data.data !== null) {
				if (deps.isWeekSaveIdle() && !deps.editingTask.value) {
					deps.setWeekKnownUpdatedAt(response.data.updatedAt)
					deps.weekData.value = normalizeWeekData(response.data.data)
					deps.materializeRecurringTasks()
				}
			}
		} catch {
			if (controller.signal.aborted) {
				return
			}
			await new Promise((resolve) => setTimeout(resolve, 5_000))
		}
		longPollWeek()
	}

	// --- Custom columns polling ---

	function stopCustomPoll() {
		shouldPollCustom = false
		customPollAbortController?.abort()
		customPollAbortController = null
	}

	async function longPollCustom() {
		if (!shouldPollCustom) {
			return
		}
		const controller = new AbortController()
		customPollAbortController = controller
		try {
			const url = generateUrl('/apps/weekplanner/custom-columns/poll')
			const response = await axios.get<{ changed: boolean, updatedAt: number, data?: unknown }>(
				`${url}?since=${deps.getCustomKnownUpdatedAt()}`,
				{ signal: controller.signal, timeout: 35_000 },
			)
			if (response.data.changed) {
				if (deps.isCustomSaveIdle() && !deps.editingTask.value) {
					deps.setCustomKnownUpdatedAt(response.data.updatedAt)
					deps.applyCustomColumnsData(response.data.data)
				}
			}
		} catch {
			if (controller.signal.aborted) {
				return
			}
			await new Promise((resolve) => setTimeout(resolve, 5_000))
		}
		longPollCustom()
	}

	// --- Lifecycle helpers ---

	function startLongPolling() {
		shouldPollWeek = true
		longPollWeek()
		shouldPollCustom = true
		longPollCustom()
	}

	function stopAllPolling() {
		stopWeekPoll()
		stopCustomPoll()
	}

	// --- Notify push ---

	async function trySetupNotifyPush(): Promise<boolean> {
		try {
			const wsUrl = rewriteNotifyPushWebsocket()
			if (!wsUrl) {
				return false
			}

			// `mod.listen()` returns truthy whenever the notify_push capability
			// is advertised, not when the WebSocket actually connects. Without
			// this probe a broken proxy or unreachable backend silently kills
			// cross-device sync because the long-poll fallback never engages.
			if (!(await probeWebSocket(wsUrl))) {
				return false
			}

			const mod = await import('@nextcloud/notify_push')

			const available = mod.listen('weekplanner_week_update', (_type, body) => {
				if (!body) {
					return
				}
				if (Number(body.year) === deps.currentYear.value && Number(body.week) === deps.currentWeek.value) {
					if (deps.isWeekSaveIdle() && deps.isWeekLoadIdle() && !deps.editingTask.value) {
						deps.loadWeek()
					}
				}
			})

			if (!available) {
				return false
			}

			mod.listen('weekplanner_customcolumns_update', () => {
				if (deps.isCustomSaveIdle() && !deps.editingTask.value) {
					deps.loadCustomColumns()
				}
			})

			return true
		} catch {
			return false
		}
	}

	function isUsingNotifyPush() {
		return usingNotifyPush
	}

	function setUsingNotifyPush(val: boolean) {
		usingNotifyPush = val
	}

	return {
		stopWeekPoll,
		startLongPolling,
		stopAllPolling,
		trySetupNotifyPush,
		isUsingNotifyPush,
		setUsingNotifyPush,
		longPollWeek,
	}
}
